### ISSUE TITLE
更新到v3后启动失败

### ISSUE THREAD

**Issue by dcty** [monyuan/smya-client#1]
![image](https://user-images.githubusercontent.com/792929/101706873-0a420800-3ac5-11eb-8ec6-e0cc42d29d78.png)

**Comment by monyuan** [comment]
无法复现，请提供一下电脑信息

**Comment by monyuan** [comment]
顺便提供一下安装目录的完整截图，我看看是不是少文件。

另外注意杀毒软件、以及微软自带的杀毒软件是否对其进行了隔离

**Comment by dcty** [comment]
卸载重装之后正常了，分别卸载了V2和V3。
