### ISSUE TITLE
作者大大客户端是不维护了嘛？

### ISSUE THREAD

**Issue by lintu666** [monyuan/smya-client#4]
我看网站上说在重构，这么久还没动静呐，现在功能还是不能用的状态

**Comment by lintu666** [comment]
不维护的话能否服务端开源呢：）

**Comment by monyuan** [comment]
你好，现在事情太忙，忙完后重新写一个开源




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月21日(星期四) 下午2:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [monyuan/smya-client] 作者大大客户端是不维护了嘛？ (Issue #4)





 
不维护的话能否服务端开源呢：）

**Comment by lintu666** [comment]
> 你好，现在事情太忙，忙完后重新写一个开源
> […](#)
> ------------------ 原始邮件 ------------------ 发件人：***@ ***.***>; 时间 22 年 22 月 日（周四下午 2 点 4 月 4 日） 20 月 20 日 ***@*** ; 抄送：***@***.***>; 主题： Re: [mon/smya-client] 嘛大客户端）是不维护了？（问题#4）不维护可以服务端开源呢：- 直接回复此邮件，在 GitHub 上查看，或者退订。您收到此消息是因为您订阅了此线程。消息 ID：***@***.***>

感谢回复，产品很棒官网社区也一直在讨论不能用的问题；加油哦希望能尽快再次使用上
